repository:
  url: https://github.com/mlcommons/inference_results_v3.0.git
  branch: main
#  url: https://github.com/mlcommons/inference_results_v4.0.git


hardware: NVIDIA
timezone: Asia/Kolkata

benchmark:
  - bert

